export type Note = {
  name: string;
  title: string;
  description: string;
  labels: string[];
  filepath?: string;
  link?: {
    url: string;
    text: string;
  };
  arguments?: string[];
};

export type Relationship = {
  from: string;
  to: string;
  labels: string[];
};

export type H3Section = {
  title: string;
  description: string;
  notes?: Note[];
  relationships?: Relationship[];
  arguments?: string[];
};

export type H2Section = {
  title: string;
  description: string;
  sections: H3Section[];
};

export type Report = {
  title: string;
  filepath: string;
  sections: H2Section[];
};

const useCase: Note = {
  name: 'usecase.io.calls.count',
  title: 'Count I/O calls per function and method',
  description: 'Returns counts keyed by function and method.',
  labels: ['usecase'],
};

const rootCall: Note = {
  name: 'cli.root',
  title: 'flyb CLI root command',
  description: 'The CLI root command for report generation and validation.',
  labels: ['call'],
  arguments: ['command=list', 'format=markdown'],
};

const relRootCallToUseCase: Relationship = {
  from: rootCall.name,
  to: useCase.name,
  labels: ['satisfies-usecase'],
};

const sectionGraphRendering: H3Section = {
  title: 'Graph rendering strategy',
  description: 'Render graph content based on graph shape and renderer arguments.',
  notes: [rootCall, useCase],
  relationships: [relRootCallToUseCase],
  arguments: ['graph-renderer=mermaid', 'cycle-policy=allow'],
};

const sectionFlowDesign: H2Section = {
  title: 'Flow design',
  description: 'Flow sections generated by the CLI.',
  sections: [sectionGraphRendering],
};

const flowDesignReport: Report = {
  title: 'Flow Design Overview',
  filepath: 'doc/FLOW_DESIGN.md',
  sections: [sectionFlowDesign],
};

// Helpful when documenting the exact JSON output shape in markdown/docs.
export const exampleNote = JSON.stringify(rootCall, null, 2);
export const exampleUseCase = JSON.stringify(useCase, null, 2);
export const exampleRelationship = JSON.stringify(
  relRootCallToUseCase,
  null,
  2,
);
export const exampleH3Section = JSON.stringify(sectionGraphRendering, null, 2);
export const exampleH2Section = JSON.stringify(sectionFlowDesign, null, 2);
export const exampleReport = JSON.stringify(flowDesignReport, null, 2);
