export type Note = {
  name: string;
  title: string;
  description: string;
  labels: string[];
  filepath?: string;
  link?: {
    url: string;
    text: string;
  };
  arguments?: string[];
};

export type Relationship = {
  from: string;
  to: string;
  labels: string[];
};

export type H3Section = {
  title: string;
  description: string;
  notes?: Note[];
  relationships?: Relationship[];
  arguments?: string[];
};

export type H2Section = {
  title: string;
  description: string;
  sections: H3Section[];
};

export type Report = {
  title: string;
  filepath: string;
  sections: H2Section[];
};

export type ArgumentRegistry = {
  version: string;
  arguments: Array<{
    name: string;
    valueType: 'string' | 'string[]' | 'boolean' | 'int' | 'float' | 'enum';
    scopes: Array<'h3-section' | 'note' | 'renderer'>;
    defaultValue?: string | string[] | boolean | number;
    allowedValues?: string[];
  }>;
};

export type OrderingPolicy = {
  // Notes: (primaryLabel, name), where primaryLabel is smallest label lexicographically.
  notes: 'by-name' | 'by-title' | 'by-label-then-name' | 'source-order';
  // Relationships: (from, to, labelsSortedJoined); labelsSortedJoined uses sorted labels joined by `|`.
  relationships: 'by-name' | 'by-title' | 'by-label-then-name' | 'source-order';
  // Sections: (lowercase(title), originalIndex).
  sections: 'by-name' | 'by-title' | 'by-label-then-name' | 'source-order';
  // Arguments: argument key/name.
  arguments: 'by-name' | 'by-title' | 'by-label-then-name' | 'source-order';
};

export type Diagnostic = {
  code: string;
  severity: 'error' | 'warning' | 'info';
  source: string;
  message: string;
  location?: string;
  noteName?: string;
  argumentName?: string;
  labelValue?: string;
};

export type GraphIntegrityPolicy = {
  missingNode: 'error' | 'warning' | 'ignore';
  orphanNode: 'error' | 'warning' | 'ignore';
  duplicateNoteName: 'error' | 'warning' | 'ignore';
  unknownRelationshipLabel: 'error' | 'warning' | 'ignore';
  crossReportReference: 'allow' | 'disallow';
};

const useCase: Note = {
  name: 'usecase.io.calls.count',
  title: 'Count I/O calls per function and method',
  description: 'Returns counts keyed by function and method.',
  labels: ['usecase'],
};

const rootCall: Note = {
  name: 'cli.root',
  title: 'flyb CLI root command',
  description: 'The CLI root command for report generation and validation.',
  labels: ['call'],
  arguments: ['command=list', 'format=markdown'],
};

const relRootCallToUseCase: Relationship = {
  from: rootCall.name,
  to: useCase.name,
  labels: ['satisfies-usecase'],
};

const sectionGraphRendering: H3Section = {
  title: 'Graph rendering strategy',
  description: 'Render graph content based on graph shape and renderer arguments.',
  notes: [rootCall, useCase],
  relationships: [relRootCallToUseCase],
  arguments: ['graph-renderer=mermaid', 'cycle-policy=allow'],
};

const sectionFlowDesign: H2Section = {
  title: 'Flow design',
  description: 'Flow sections generated by the CLI.',
  sections: [sectionGraphRendering],
};

const flowDesignReport: Report = {
  title: 'Flow Design Overview',
  filepath: 'doc/FLOW_DESIGN.md',
  sections: [sectionFlowDesign],
};

const argumentRegistry: ArgumentRegistry = {
  version: 'v1',
  arguments: [
    {
      name: 'format-csv',
      valueType: 'enum',
      scopes: ['note'],
      defaultValue: 'md',
      allowedValues: ['md', 'csv'],
    },
    {
      name: 'graph-renderer',
      valueType: 'enum',
      scopes: ['h3-section', 'renderer'],
      defaultValue: 'markdown-text',
      allowedValues: ['markdown-text', 'mermaid'],
    },
    {
      name: 'cycle-policy',
      valueType: 'enum',
      scopes: ['h3-section'],
      defaultValue: 'disallow',
      allowedValues: ['disallow', 'allow', 'collapse'],
    },
    {
      name: 'show-legend',
      valueType: 'boolean',
      scopes: ['renderer'],
      defaultValue: true,
    },
  ],
};

const orderingPolicy: OrderingPolicy = {
  notes: 'by-label-then-name',
  relationships: 'by-name',
  sections: 'by-title',
  arguments: 'by-name',
};

const validationDiagnostic: Diagnostic = {
  code: 'LABEL_REF_UNKNOWN',
  severity: 'warning',
  source: 'labels.reference.validate',
  message:
    'Label reference `unknown-tag` is not present in dataset labels (note.labels and relationship.labels union).',
  location: 'reports[0].sections[0].arguments[1]',
  argumentName: 'select-labels',
  labelValue: 'unknown-tag',
};

const graphIntegrityPolicy: GraphIntegrityPolicy = {
  missingNode: 'error',
  orphanNode: 'warning',
  duplicateNoteName: 'error',
  unknownRelationshipLabel: 'warning',
  crossReportReference: 'disallow',
};

// Helpful when documenting the exact JSON output shape in markdown/docs.
export const exampleNote = JSON.stringify(rootCall, null, 2);
export const exampleUseCase = JSON.stringify(useCase, null, 2);
export const exampleRelationship = JSON.stringify(
  relRootCallToUseCase,
  null,
  2,
);
export const exampleH3Section = JSON.stringify(sectionGraphRendering, null, 2);
export const exampleH2Section = JSON.stringify(sectionFlowDesign, null, 2);
export const exampleReport = JSON.stringify(flowDesignReport, null, 2);
export const exampleArgumentRegistry = JSON.stringify(argumentRegistry, null, 2);
export const exampleOrderingPolicy = JSON.stringify(orderingPolicy, null, 2);
export const exampleDiagnostic = JSON.stringify(validationDiagnostic, null, 2);
export const exampleGraphIntegrityPolicy = JSON.stringify(
  graphIntegrityPolicy,
  null,
  2,
);
