locator: internal/validate/app_data_config_args.go
meta:
  function_list:
    - validateConfiguredArguments
  import_files_list:
    - fmt
    - github.com/flarebyte/baldrick-flying-buttress/internal/domain
  language: go
